### ISSUE TITLE
qouted printable encoding of names in headers wrong in some cases

### ISSUE THREAD

**Issue by johnyb** [whiteout-io/mailbuild#16]
According to https://tools.ietf.org/html/rfc2047#section-5 Point (3):

```
In this case the set of characters that may be used in a "Q"-encoded
'encoded-word' is restricted to: <upper and lower case ASCII
letters, decimal digits, "!", "*", "+", "-", "/", "=", and "_"
(underscore, ASCII 95.)>.
```

This part is not respected when encoding the header fields using this library. I have the following code:

```JavaScript
var MB = require('mailbuild');
var node = new MB();
node.setHeader('from', '"Drescher, Mäh" <maeh.drescher@landmaschi.ne>');
node.build();
//'From: =?UTF-8?Q?Drescher,_M=C3=A4h?= <maeh.drescher@landmaschi.ne>\r\nDate: Wed, 23 Sep 2015 14:40:18 +0000\r\nMessage-Id: <1443019368877-be928e95-cd6db395-466fc88b@landmaschi.ne>\r\nMIME-Version: 1.0\r\n'
```

Which, when send to a standards compliant (RFC 822) mime parser will fail. I tried to provide a fix for this, but thought, I'd start a discussion before going on.

The most easy fix I can see, is to just use base64 encoding for address names, so in `MimeNode.prototype._encodeAddressName` I just changed the call to `mimefuncs.mimeWordEncode(name, 'B', 52);`. I'm unsure what side-effects this has. I'm also unsure how to exactly approach this issue. This easy solution is very similar to the proposal of issue #14. So this might be a valid approach.

Another approach is to replace all illegal characters with their encoded form, after quoted-printable encoding. Of course this is also only needed for `_encodeAddressName`, as such characters are totally fine in other headers, like "Subject".

I'd really like to hear your opinion on this :)

**Comment by andris9** [comment]
Yes, you're right, the comma shouldn't be there. Quoted printable in mime encoded words is more restrictive than regular quoted printable encoding. What this library does is to make encoded words is to use normal quoted printable encoding and then replace all whitespaces in the result (see [here](https://github.com/whiteout-io/mimefuncs/blob/master/src/mimefuncs.js#L229)).

**Comment by andris9** [comment]
I updated the character ranges in the *mimefuncs* module that handles quoted printable encoding (https://github.com/whiteout-io/mimefuncs/commit/aa61a74de856fa889eb1445b8ce3dab335beab8b) to be more strict. This change is probably going to break a lot of tests downstream so I have no idea when the update is going be released to npm.
